### ISSUE TITLE
sys161: Cannot open boot image kernel: No such file or directory

### ISSUE THREAD

**Issue by rahulroxx** [ops-class/os161#2]
Hi, 
I'm new to operating system developement  . I have been following along ASST0 and encountered error . 

Could you please Explain 3.3 - 3.6 Sections ( configuring and building )  in ASST0. 
Host OS - Ubuntu 14.04 ( toolchain installed ) 
Thanks, 
Rahul Rao

**Comment by xcv58** [comment]
Could you provide more detail about your error?

**Comment by rahulroxx** [comment]
bmake depend shows me this 


> (cd kern && bmake depend)
> (cd userland && bmake depend)
> (cd lib && bmake depend)
> (cd crt0 && bmake depend)
> mips-harvard-os161-gcc -O2 -Wall -W -Wwrite-strings -Wmissing-prototypes -Werror -std=gnu99 -mno-abicalls -fno-pic -nostdinc  -I../../../build/install/include -M mips/crt0.S | ../../../mk/fixdepends.sh '../../../build/install' native  > ../../../build/userland/lib/crt0/.deptmp
> mv -f ../../../build/userland/lib/crt0/.deptmp ../../../build/userland/lib/crt0/.depend
> (cd libc && bmake depend)
> bmake ../../../build/userland/lib/libc/syscalls.S
> 
> bmake[4]: stopped in /home/rahul/Desktop/gits/src/os161/userland/lib/libc
> *** Error code 2
> 
> Stop.
> bmake[3]: stopped in /home/rahul/Desktop/gits/src/os161/userland/lib/libc
> *** Error code 1
> 
> Stop.
> bmake[2]: stopped in /home/rahul/Desktop/gits/src/os161/userland/lib
> *** Error code 1
> 
> Stop.
> bmake[1]: stopped in /home/rahul/Desktop/gits/src/os161/userland
> *** Error code 1
> 
> Stop.
> bmake: stopped in /home/rahul/Desktop/gits/src/os161
>

**Comment by rahulroxx** [comment]
Apologies, 
It was hard follow along the written tutorial on the site specially Section 3.3 onwards. but video makes it more clear . 
for eg- ./configure DUMBVM wasn't told in the written tutorial and furthur it was ambiguous where to run bmake ?
