### ISSUE TITLE
Error Unknown syscall infinite loop 

### ISSUE THREAD

**Issue by rahulroxx** [ops-class/os161#3]
sys161 kernel
press 's' 

```
Unknown syscall 55
Unknown syscall 50
Unknown syscall 55
Unknown syscall 50
Unknown syscall 55
Unknown syscall 50
Unknown syscall 55
Unknown syscall 50
Unknown syscall 55
Unknown syscall 50
Unknown syscall 55
Unknown syscall 50
Unknown syscall 55
Unknown syscall 50
Unknown syscall 55
Unknown syscall 50
Unknown syscall 55
Unknown syscall 50
Unknown syscall 55
Unknown syscall 50
Unknown syscall 55
Unknown syscall 50

```

which runs infinite number of times.

**Comment by xcv58** [comment]
Because you haven't implemented related system calls.
Below files may give you some hints:
https://github.com/ops-class/os161/blob/master/kern/include/kern/syscall.h#L115
https://github.com/ops-class/os161/blob/master/kern/arch/mips/syscall/syscall.c#L40

**Comment by rahulroxx** [comment]
Thanks @xcv58 . Can i boot kernel image on my PC ( 64 bit compatible ) ?

**Comment by jtdroste** [comment]
os161 is written using the MIPS architecture, so no.  You would be running it through a simulator (sys161).
