### ISSUE TITLE
Error when building userland on Ubuntu 14.04.05 LTS

### ISSUE THREAD

**Issue by TylerBrock** [ops-class/os161#5]
Hey everyone,

I'm following along at home but having some trouble building the userland for os161. I'm running Ubuntu 14.05.5 with the PPA packages installed:

```
tbrock@ops-class:~/os161/userland$ uname -a
Linux ops-class 4.4.0-47-generic #68~14.04.1-Ubuntu SMP Wed Oct 26 19:42:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
tbrock@ops-class:~/os161/userland$ cat /etc/issue
Ubuntu 14.04.5 LTS \n \l
```

When I run `bmake` at the top level of the os161 directory I see the following error at the end of the output:

```
gcc -O2 -Wall -W -Wwrite-strings -Wmissing-prototypes -Werror  -I../../../build/install/hostinclude -DDECLARE_NTOHLL -DNEED_NTOHLL -DHOST -c err.c -o ../../../build/userland/lib/hostcompat/err.ho
bmake[2]: exec(gcc) failed (No such file or directory)
*** Error code 1

Stop.
bmake[2]: stopped in /home/tbrock/os161/lib/hostcompat
*** Error code 1

Stop.
bmake[1]: stopped in /home/tbrock/os161/userland/lib
*** Error code 1

Stop.
bmake: stopped in /home/tbrock/os161/userland
```

I see err.c in `build/userland/lib/hostcompat` so not sure what is going on here. Any help would be greatly appreciated.

**Comment by TylerBrock** [comment]
Doh, this box didn't have gcc installed. Fixed by simply running `sudo apt install gcc`. This box is fresh!

**Comment by TylerBrock** [comment]
Although, now I'm not sure what compiler built the kernel I ran before building/running the userland... possible that the other configure script detects clang but the userland configure does not?

**Comment by gchallen** [comment]
There are two compilers that are used: a cross-compiler that builds the MIPS r3000(ish) binaries that get used by sys161, and then a separate host compiler that builds binaries to run on the host system. A few of the OS/161 userland binaries also build versions that you can run natively for testing purposes. Hopefully this is fixed on our new boxes...
