### ISSUE TITLE
Lock Test Suite Not Fully Comprehensive

### ISSUE THREAD

**Issue by zsmoore** [ops-class/os161#7]
It is possible to receive full credit for locks without actually having properly implemented locks.

If you implement locks with a boolean for whether the lock is held or not rather than holding a thread you will almost always pass the test suite if your lock do I hold returns only that boolean.

The test suite should have a test in which a lock is created and calls lock do I hold while another thread holds the lock.  If lock do I hold returns true the test should fail.

**Note:** A new pull request has been created to address this issue.

**Comment by gchallen** [comment]
In general, we never promise that our tests suites will hit all corner cases. Although we are trying. Thanks for the PR—will take a look.
